CREATE SCHEMA IF NOT EXISTS jardineria ;
USE jardineria ;

CREATE TABLE IF NOT EXISTS oficinas (
  CODIGOOFICINA VARCHAR(10) NOT NULL,
  CIUDAD VARCHAR(30) NOT NULL,
  PAIS VARCHAR(50) NOT NULL,
  REGION VARCHAR(50)  DEFAULT NULL,
  CODIGOPOSTAL VARCHAR(10) NOT NULL,
  TELEFONO VARCHAR(20) NOT NULL,
  LINEADIRECCION1 VARCHAR(50) NOT NULL,
  LINEADIRECCION2 VARCHAR(50)  DEFAULT NULL,
  PRIMARY KEY (CODIGOOFICINA));

CREATE TABLE IF NOT EXISTS empleados (
  CODIGOEMPLEADO INT NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDO1 VARCHAR(50) NOT NULL,
  APELLIDO2 VARCHAR(50)  DEFAULT NULL,
  EXTENSION VARCHAR(10) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  CODIGOOFICINA VARCHAR(10) NOT NULL,
  CODIGOJEFE INT  DEFAULT NULL,
  PUESTO VARCHAR(50)  DEFAULT NULL,
  PRIMARY KEY (CODIGOEMPLEADO),
  CONSTRAINT EMPLEADOS_EMPLEADOSFK FOREIGN KEY (CODIGOJEFE)REFERENCES empleados (CODIGOEMPLEADO),
  CONSTRAINT EMPLEADOS_OFICINASFKFOREIGN KEY (CODIGOOFICINA) REFERENCES oficinas (CODIGOOFICINA));

CREATE TABLE IF NOT EXISTS clientes (
  CODIGOCLIENTE INT NOT NULL,
  NOMBRECLIENTE VARCHAR(50)  DEFAULT NULL,
  NOMBRECONTACTO VARCHAR(30)  DEFAULT NULL,
  APELLIDOCONTACTO VARCHAR(30)  DEFAULT NULL,
  TELEFONO VARCHAR(15)  DEFAULT NULL,
  FAX VARCHAR(15)  DEFAULT NULL,
  LINEADIRECCION1 VARCHAR(50)  DEFAULT NULL,
  LINEADIRECCION2 VARCHAR(50)  DEFAULT NULL,
  CIUDAD VARCHAR(50)  DEFAULT NULL,
  REGION VARCHAR(50)  DEFAULT NULL,
  PAIS VARCHAR(50)  DEFAULT NULL,
  CODIGOPOSTAL VARCHAR(10)  DEFAULT NULL,
  CODIGOEMPLEADOREPVENTAS INT  DEFAULT NULL,
  LIMITECREDITO INT  DEFAULT NULL,
  PRIMARY KEY (CODIGOCLIENTE),
  CONSTRAINT CLIENTES_EMPLEADOSFK FOREIGN KEY (CODIGOEMPLEADOREPVENTAS) REFERENCES empleados (CODIGOEMPLEADO));

CREATE TABLE IF NOT EXISTS pedidos (
  CODIGOPEDIDO INT NOT NULL,
  FECHAPEDIDO DATE NOT NULL,
  FECHAESPERADA DATE  DEFAULT NULL,
  FECHAENTREGA DATE  DEFAULT NULL,
  ESTADO VARCHAR(15) NOT NULL,
  COMENTARIOS VARCHAR(600)  DEFAULT NULL,
  CODIGOCLIENTE INT NOT NULL,
  PRIMARY KEY (CODIGOPEDIDO),
  CONSTRAINT PEDIDOS_CLIENTE
    FOREIGN KEY (CODIGOCLIENTE)
    REFERENCES clientes (CODIGOCLIENTE));

CREATE TABLE IF NOT EXISTS gamasproductos (
  GAMA VARCHAR(50) NOT NULL,
  DESCRIPCIONTEXTO VARCHAR(600)  DEFAULT NULL,
  DESCRIPCIONHTML VARCHAR(600)  DEFAULT NULL,
  IMAGEN BLOB  DEFAULT NULL,
  PRIMARY KEY (GAMA));

CREATE TABLE IF NOT EXISTS productos (
  CODIGOPRODUCTO VARCHAR(15) NOT NULL,
  NOMBRE VARCHAR(70) NOT NULL,
  GAMA VARCHAR(50) NOT NULL,
  DIMENSIONES VARCHAR(25)  DEFAULT NULL,
  PROVEEDOR VARCHAR(50)  DEFAULT NULL,
  DESCRIPCION VARCHAR(600)  DEFAULT NULL,
  CANTIDADENSTOCK INT NOT NULL,
  PRECIOVENTA INT NOT NULL,
  PRECIOPROVEEDOR INT  DEFAULT NULL,
  PRIMARY KEY (CODIGOPRODUCTO),
  CONSTRAINT PRODUCTOS_GAMAFK FOREIGN KEY (GAMA) REFERENCES gamasproductos (GAMA));


CREATE TABLE IF NOT EXISTS detallepedidos (
  CODIGOPEDIDO INT NOT NULL,
  CODIGOPRODUCTO VARCHAR(15) NOT NULL,
  CANTIDAD INT NOT NULL,
  PRECIOUNIDAD INT NOT NULL,
  NUMEROLINEA INT NOT NULL,
  PRIMARY KEY (CODIGOPEDIDO, CODIGOPRODUCTO),
  CONSTRAINT DETALLEPEDIDOS_PEDIDOFK FOREIGN KEY (CODIGOPEDIDO) REFERENCES pedidos (CODIGOPEDIDO),
  CONSTRAINT DETALLEPEDIDOS_PRODUCTOFK FOREIGN KEY (CODIGOPRODUCTO) REFERENCES productos (CODIGOPRODUCTO));


CREATE TABLE IF NOT EXISTS pagos (
  CODIGOCLIENTE INT NOT NULL,
  FORMAPAGO VARCHAR(40) NOT NULL,
  IDTRANSACCION VARCHAR(50) NOT NULL,
  FECHAPAGO DATE NOT NULL,
  CANTIDAD INT NOT NULL,
  PRIMARY KEY (CODIGOCLIENTE, IDTRANSACCION),
  CONSTRAINT PAGOS_CLIENTEFK FOREIGN KEY (CODIGOCLIENTE) REFERENCES clientes (CODIGOCLIENTE));
